additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: adib.co.eg
 
compute:
- architecture: amd64
  name: worker
  platform: {}
  replicas: 0
 
controlPlane:
  architecture: amd64
  name: master
  platform: {}
  replicas: 3
 
metadata:
  name: ocp-poc
 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - 10.217.0.0/16
  networkType: OVNKubernetes
 
platform:
  vsphere:
    failureDomains:
    - name: adib-fd
      region: ocp-poc-region
      server: 10.240.38.150
      topology:
        computeCluster: "/DC_Site/host/DC Prod"
        datacenter: DC_Site
        datastore: "/DC_Site/datastore/OpenShift_LAB_NRPL"
        networks:
        - VLAN_47_319
        resourcePool: "/DC_Site/host/DC Prod/Resources"
        folder: "/DC_Site/vm/Openshift/POC/"
      zone: ocp-poc-zone
    vcenters:
    - datacenters:
      - DC_Site
      password: P@ssw0rd
      port: 443
      server: 10.240.38.150
      user: kubs@adib.co.eg
    diskType: thin
 
proxy:
  httpProxy: http://172.22.4.185:8080
  httpsProxy: http://172.22.4.185:8080
  noProxy: .adib.co.eg,10.240.47.160/27,10.240.38.150,10.240.48.11,10.240.47.0/24
 
fips: false
 
pullSecret: >
  {"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNmQyM2MzNzM3NmQwNDQ3MmI5OTU0Y2ExZmE1MWJiZmY6WFBLNlBPQ0RFQUgxUkxKM0kzOE1KV1hEVlgyOERQN0pZU0xKUVRLNFdBSzBERFJXTE8zRDFPS0JUNkNCQzVESA==","email":"abdelrahman.s.mohamed@adib.eg"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNmQyM2MzNzM3NmQwNDQ3MmI5OTU0Y2ExZmE1MWJiZmY6WFBLNlBPQ0RFQUgxUkxKM0kzOE1KV1hEVlgyOERQN0pZU0xKUVRLNFdBSzBERFJXTE8zRDFPS0JUNkNCQzVESA==","email":"abdelrahman.s.mohamed@adib.eg"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLThhMWEzMmNlLTFkYWUtNGEzNi1iZGU1LWNhM2UxZjhjZDM5OTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtPVGczWkdObU16UTBNekEwTkdNNU9HVTFZbVpsWlRKaE9EQTBaamt6WWlKOS5RZ1ducTItZ2doenpqbFljU3JjNmx4ME12NFVwbVNrQzJWMHdlQnU0SVlQaFc5VVE4SXNyTUFKazRUVVQzMnp5YnBTZTU3NXlXcU9kVU9wcnNfUFBXdzRvX0k1cmEwMmNyX3NJN1V6b3BMeXRDQl9PakV5VjdPeTktSk1sSm13d21VejZfRklEYjdyMDBzTE5BdFFTQk9HZFpqYXVoNnZnX0l6aVhTX1Jqal9nRl81SGFlUW4yRW94V2FMU2JJclJaNDlwQm9CcUtGTzczRkh6SE01UU92QlJaREFkN3l3cGQ5VTE4dEszTkVWOVVUWk90cHJCT3V4YWZrY2tIZE5qVHRLc1dWbjBuRXlVc2VyejFBUTNtZlQyQ3R2WVF3M3NnS3huTnBjN3ZnY3dKOGwtNHN0UzdvMTRKdUNuSXVuMlhCUVRURFlOUEN1RS1FNm5FbHhRV2lQTlFCWWhoMTR3QjM2TFQ4SnpqdVVVYW5DeGMxdmxFOEFKcUJETWg2bEtBa1B1b1ZSbzRYby16amE3ZDR4UHNsdzVkXzFNNEx1a1lEOVhTTzcwZVlFbXl6QmhXX2FmRkZvTG51X2U2RDdoSDhpOWNWUmxtMEwxNHM1NFRnelZnNF9CMGE3LUo0YlQ0elFYbUNBRGFiT09rY0gzU1pSM0ctV0hJSXM2VFB5TnRkOW4yRTJoWFBJdmw1LXcyMEg1NEZJNm1UZ08wYUdtVG5wckhzQzJfRWZIYUpFVzIzVjZkbnhCTHhWdXBEU2ZQejFVb0VpWDVXZ3V1c1BIcVU5eVZ6anFFajFienF6MlJERmlkOEdIQlM5ZDA1UDdHR3ZoT2loRWtLemZRaXlKVVZ3QlRBYWxjZ0J2NU42aERSZUl2MzF1Y0ZxN2NfdFNzRk05U3MxV1BrZw==","email":"abdelrahman.s.mohamed@adib.eg"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLThhMWEzMmNlLTFkYWUtNGEzNi1iZGU1LWNhM2UxZjhjZDM5OTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtPVGczWkdObU16UTBNekEwTkdNNU9HVTFZbVpsWlRKaE9EQTBaamt6WWlKOS5RZ1ducTItZ2doenpqbFljU3JjNmx4ME12NFVwbVNrQzJWMHdlQnU0SVlQaFc5VVE4SXNyTUFKazRUVVQzMnp5YnBTZTU3NXlXcU9kVU9wcnNfUFBXdzRvX0k1cmEwMmNyX3NJN1V6b3BMeXRDQl9PakV5VjdPeTktSk1sSm13d21VejZfRklEYjdyMDBzTE5BdFFTQk9HZFpqYXVoNnZnX0l6aVhTX1Jqal9nRl81SGFlUW4yRW94V2FMU2JJclJaNDlwQm9CcUtGTzczRkh6SE01UU92QlJaREFkN3l3cGQ5VTE4dEszTkVWOVVUWk90cHJCT3V4YWZrY2tIZE5qVHRLc1dWbjBuRXlVc2VyejFBUTNtZlQyQ3R2WVF3M3NnS3huTnBjN3ZnY3dKOGwtNHN0UzdvMTRKdUNuSXVuMlhCUVRURFlOUEN1RS1FNm5FbHhRV2lQTlFCWWhoMTR3QjM2TFQ4SnpqdVVVYW5DeGMxdmxFOEFKcUJETWg2bEtBa1B1b1ZSbzRYby16amE3ZDR4UHNsdzVkXzFNNEx1a1lEOVhTTzcwZVlFbXl6QmhXX2FmRkZvTG51X2U2RDdoSDhpOWNWUmxtMEwxNHM1NFRnelZnNF9CMGE3LUo0YlQ0elFYbUNBRGFiT09rY0gzU1pSM0ctV0hJSXM2VFB5TnRkOW4yRTJoWFBJdmw1LXcyMEg1NEZJNm1UZ08wYUdtVG5wckhzQzJfRWZIYUpFVzIzVjZkbnhCTHhWdXBEU2ZQejFVb0VpWDVXZ3V1c1BIcVU5eVZ6anFFajFienF6MlJERmlkOEdIQlM5ZDA1UDdHR3ZoT2loRWtLemZRaXlKVVZ3QlRBYWxjZ0J2NU42aERSZUl2MzF1Y0ZxN2NfdFNzRk05U3MxV1BrZw==","email":"abdelrahman.s.mohamed@adib.eg"}}}

 
sshKey: >
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKE9xZ+7wxQlvEqei3W4OjKCBSuIzsM6o7KUU9oI5xSs root@P_Installer
